# Generated by Django 3.2.9 on 2021-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=64)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('published', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('categories', models.ManyToManyField(blank=True, related_name='events', to='event.Category')),
            ],
        ),
    ]
